spring:
  datasource:
    url: jdbc:mysql://${mc.datasource.ip}:3306/msp_user_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${mc.datasource.username}
    password: ${mc.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mc.common.model
  global-config:
    db-config:
      id-type: auto

mc:
  swagger:
    enabled: true
    title: 用户中心
    description: 用户中心接口文档
    version: 1.0
    base-package: com.mc.user.controller
  cache-manager:
    configs:
    - key: menu
      second: 300
    - key: user
      second: 1800
  #多租户配置
  tenant:
    enable: true
    ignoreTables:
    - sys_user
    - sys_role_user
    - sys_role_menu