spring:
  datasource:
    url: jdbc:mysql://${mc.datasource.ip}:3306/msp_oauth_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${mc.datasource.username}
    password: ${mc.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mc.oauth.model
  global-config:
    db-config:
      id-type: auto

mc:
  oauth2:
    token:
      store:
        type: redis
  swagger:
    enabled: true
    title: 认证中心
    description: 认证中心接口文档
    version: 1.0
    base-package: com.mc.oauth.controller
  security:
    code:
      # 忽略验证码的应用编号
      ignoreClientCode: app