spring:
  data:
    elasticsearch:
      cluster-name: ${mc.elasticsearch.cluster-name}
      cluster-nodes: ${mc.elasticsearch.cluster-nodes}:9300
  elasticsearch:
    rest:
      uris: ${mc.elasticsearch.cluster-nodes}:9200

mc:
  indices:
    show: sys-log-*, mysql-slowlog-*, sys_user, point-log-*
  swagger:
    enabled: true
    title: 搜索中心
    description: 搜索中心接口文档
    version: 1.0
    base-package: com.mc.search.controller